{{- if not .Values.tls.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "auth-service.fullname" . }}-tls
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ (required "Certificate PEM is required" .Values.tls.certificatePEM) | b64enc | quote }}
  tls.ley: {{ (required "Key PEM is required" .Values.tls.keyPEM) | b64enc | quote }}
{{- end }}
