apiVersion: v2
name: rvrd
description: Metachart for the RvRD demo organization
type: application
version: 0.112.0
appVersion: 0.112.0

dependencies:
  - name: dex
    version: 2.13.0
    repository: "@stable"
